In [2]:
import numpy as np


In [17]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(" print this shhit out of the array\n ",array[0]) 


 print this shhit out of the array
  [1 2 3]


In [23]:
sorted_arr = np.sort(np.array([5, 1, 4, 2, 3]))
print(sorted_arr)


[1 2 3 4 5]


In [3]:
np_sorted = np.sort(np.array([1,2,3,4,5]))
print(np_sorted)

[1 2 3 4 5]
