In [2]:
import numpy as np


In [ ]:
arr1 = np.array([1, 2, 3 , 4 ,5])
print(type(arr1))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [15]:
arr2 = np.array(arr1)
arr2 = arr2.reshape(1,-1)
print(arr2)

[[1 2 3]]


In [ ]:
arr = np.array([[1, 2, 3 ,4], [5, 6 , 7 ,8] , [9, 10 ,11 ,12]])
print(" array shape: \n ", arr)

 array shape:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
arr[1: , 1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
arr[0 ,0 ] = 100
print(arr)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [34]:
arr[2,3]

np.int64(12)