In [2]:
import numpy as np


In [3]:
def greet(a):
    return f"Hello, {a}!"

In [8]:
greet("a")


'Hello, a!'

In [9]:
def greet(name):
    print(f"Hello {name}")


In [14]:
list1 = [1, 2, 3, 4, 5]


In [16]:
list1[2] = 3.5
print(list1)

[1, 2, 3.5, 4, 5]


In [17]:
numbers = [ 1, 2, 3, 4, 5 ]


In [19]:
for index , value in enumerate(numbers):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: 1
Index: 1, Value: 2
Index: 2, Value: 3
Index: 3, Value: 4
Index: 4, Value: 5


In [26]:
list1.append(5)

In [27]:
print(list1)

[1, 2, 3.5, 4, 5, 6, 6, 5, 5, 5, 5, 5]


In [28]:
total = 0 

for n in numbers:
    total += n

print(total)

15


In [1]:
age = int(input("Enter your age :"))
print("Your age is :", age)

Your age is : 56


In [2]:
age = 23
citizen = True 

if age >= 18 and citizen:
    print("You are eligible to vote.")
else :
    print("You are not eligible to vote.")


You are eligible to vote.


In [3]:
has_id = False
has_passport = True

if has_id or has_passport:
    print("Identity verified")


Identity verified


In [4]:
is_logged_in = False

if not is_logged_in:
    print("Please login")



Please login


In [6]:
x = 7 

while x < 8 :
   
    print("x is now :", x)
    x += 1


x is now : 7


In [16]:
x = 1

while x <= 5 :
    print("Current value of x :", x)
    x += 1

Current value of x : 1
Current value of x : 2
Current value of x : 3
Current value of x : 4
Current value of x : 5


In [23]:
x = 1

while x <= 5:
    print(x)
    x = x + 1


1
2
3
4
5


In [26]:
password = ""

while password != "admin":
    password = input("Enter password: ")


In [33]:
for i in range(5):
    print("Iteration number:", i)

Iteration number: 0
Iteration number: 1
Iteration number: 2
Iteration number: 3
Iteration number: 4


In [34]:
for i in range(1, 6):
    print("Iteration number:", i)

Iteration number: 1
Iteration number: 2
Iteration number: 3
Iteration number: 4
Iteration number: 5


In [35]:
for i in range(0 , 10 , 2):
    print(f"Print the branch {i}")

Print the branch 0
Print the branch 2
Print the branch 4
Print the branch 6
Print the branch 8


In [ ]:
total = 0

for i in range(1, 6):
    total = total + i
print("Total sum from 1 to 5 is:", total)

Total sum from 1 to 5 is: 15


In [29]:
unique_numbers = set([1, 2, 2, 3])


In [30]:
print(unique_numbers)

{1, 2, 3}


In [31]:
unique_numbers.add(4)
print(unique_numbers)


{1, 2, 3, 4}


In [15]:
arr2 = np.array(arr1)
arr2 = arr2.reshape(1,-1)
print(arr2)

[[1 2 3]]


In [ ]:
arr = np.array([[1, 2, 3 ,4], [5, 6 , 7 ,8] , [9, 10 ,11 ,12]])
print(" array shape: \n ", arr)

 array shape:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
arr[1: , 1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
arr[0 ,0 ] = 100
print(arr)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [34]:
arr[2,3]

np.int64(12)

In [1]:
nums = [2, 4, 6, 8]
total = 0

for x in nums:
    total += x

mean = total / len(nums)
print(mean)


5.0


In [2]:
# Write a loop to compute the sum of squares of a list:
# Example: [1,2,3] → 1²+2²+3² = 14
numbers = [1, 2, 3]
sum_of_squares = 0
for num in numbers:
    sum_of_squares += num ** 2
print(sum_of_squares)  # Output: 14


14


In [7]:
number = [ 2 ,4 , 6 , 8]
sum_of_squares = 0

for x in number:
    sum_of_squares  += x ** 2

print(mean)

30.0


In [8]:
def add(a , b):
    return a + b

In [9]:
add( 24 ,34)

58

In [21]:
import numpy as np

In [22]:
def mse(y_pred , y_true):
    y = y_pred - y_true
    y = y ** 2
    return p.mean(y)


In [29]:
mse(np.array([3, -0.5, 2, 7]) , np.array([2.5 , 0.0 , 2 , 8]))

np.float64(0.375)

In [34]:
# Create a dictionary student with:

student = {
    "name": "John Doe",
    "age": 21,
    "skills": ["Python", "Data Analysis", "Machine Learning"]
}

In [37]:
print(student["age"])

21
